model:
  type: RandomForest
  parameters:
    n_estimators: 100
    max_depth: 10

data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv

hyperparameters:
  learning_rate: 0.01
  batch_size: 32